name = "bc-trackvision"
main = "worker.js"
compatibility_date = "2025-11-07"

[assets]
directory = "./"
binding   = "ASSETS"

[[r2_buckets]]
binding     = "trackvision_bucket"
bucket_name = "trackvision"